### ISSUE TITLE
ERROR：Edncnn and MLPF failed to run

### ISSUE THREAD

**Issue by zhuyang210** [KugaMaxx/cuke-emlb#13]
Hello, I encountered problems when running Edncnn and MLPF, but it ran normally when testing other algorithms. This seems to be related to my libtorch, but there was no error when I was using cmake. Can you help me solve this problem?

```python
python eval_denoisor.py                     \
--file './data/demo/samples/demo-01.aedat4' \
--denoisor 'endcnn'                  
Before filter >>>
  Storage containing 319512 elements within 510990µs duration; time range within [1643243628737093; 1643243629248083], 
  ESR score: 1.013
eval_denoisor.py:50: RuntimeWarning: Mean of empty slice.
  print(f"After filter <<<\n  {data['events']}, \n  ESR score: {score.mean():.3f}")
/home/njit5/anaconda3/envs/emlb/lib/python3.8/site-packages/numpy/core/_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
After filter <<<
  Storage containing 4256 elements within 509895µs duration; time range within [1643243628737093; 1643243629246988], 
  ESR score: nan
``` 
```python
python eval_benchmark.py  \
--input_path './data'     \
--output_path './result'  \
--denoisor 'mlpf' --store_result --store_score
#Denoisor:    mlpf,  #Dataset:      D-END (1/1),  #Sequence: Architecture-ND00-1:   0%|                                                                          | 0/12 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "eval_benchmark.py", line 66, in <module>
    data["events"] = model.generateEvents()
  File "/media/njit5/39e16d05-05ba-46b4-bc9b-47b3c98f1d4f/zy/cuke-emlb/configs/denoisors.py", line 29, in generateEvents
    return self.model.generateEvents()
RuntimeError: _ivalue_INTERNAL ASSERT FAILED at "../torch/csrc/jit/api/object.cpp":19, please report a bug to PyTorch. 
Exception raised from _ivalue at ../torch/csrc/jit/api/object.cpp:19 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6b (0x7f244749a70b in /media/njit5/39e16d05-05ba-46b4-bc9b-47b3c98f1d4f/zy/cuke-emlb/libtorch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 0xd1 (0x7f2447496571 in /media/njit5/39e16d05-05ba-46b4-bc9b-47b3c98f1d4f/zy/cuke-emlb/libtorch/lib/libc10.so)
frame #2: <unknown function> + 0x386257b (0x7f23736c257b in /media/njit5/39e16d05-05ba-46b4-bc9b-47b3c98f1d4f/zy/cuke-emlb/libtorch/lib/libtorch_cpu.so)
frame #3: torch::jit::Object::find_method(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const + 0x36 (0x7f23736c29a6 in /media/njit5/39e16d05-05ba-46b4-bc9b-47b3c98f1d4f/zy/cuke-emlb/libtorch/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0x2e92f (0x7f2447fa692f in /media/njit5/39e16d05-05ba-46b4-bc9b-47b3c98f1d4f/zy/cuke-emlb/modules/python/multi_layer_perceptron_filter.cpython-38-x86_64-linux-gnu.so)
frame #5: <unknown function> + 0x30727 (0x7f2447fa8727 in /media/njit5/39e16d05-05ba-46b4-bc9b-47b3c98f1d4f/zy/cuke-emlb/modules/python/multi_layer_perceptron_filter.cpython-38-x86_64-linux-gnu.so)
frame #6: <unknown function> + 0x3685f (0x7f2447fae85f in /media/njit5/39e16d05-05ba-46b4-bc9b-47b3c98f1d4f/zy/cuke-emlb/modules/python/multi_layer_perceptron_filter.cpython-38-x86_64-linux-gnu.so)
frame #7: <unknown function> + 0x2585c (0x7f2447f9d85c in /media/njit5/39e16d05-05ba-46b4-bc9b-47b3c98f1d4f/zy/cuke-emlb/modules/python/multi_layer_perceptron_filter.cpython-38-x86_64-linux-gnu.so)
<omitting python frames>
frame #10: python() [0x4f587d]
frame #17: python() [0x5a5da1]
frame #18: python() [0x5a4daf]
frame #19: python() [0x45c624]
frame #21: python() [0x44fcae]
frame #23: __libc_start_main + 0xe7 (0x7f244eba6c87 in /lib/x86_64-linux-gnu/libc.so.6)
frame #24: python() [0x579f8d]
```

**Comment by ZFD-1** [comment]
I met exactly the same error. Have you ever solved it?

**Comment by GodLiu1** [comment]
I met exactly the same error. Have you ever solved it?
